name: Build KernelSU For MI8SE(sirius)

on:
  watch:
    types: [started]

jobs:
  KSUForSirius:
    runs-on: ubuntu-latest
    steps:
      - name: Preparing the path
        run: |
          sudo apt update -y
          sudo apt-get install -y zip zipalign bc build-essential zip gcc clang libc6 curl libstdc++6 git wget libssl-dev cpio
          curl -sL https://git.io/file-transfer | bash -s beta
      - name: Cloning Source Code and Toolchain
        run: |
          git clone https://github.com/SakuraNotStupid/android_kernel_xiaomi_sdm710 --depth=1 -b lineage-20_KSU
          git clone https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r445002 --depth=1 --single-branch --no-tags -b 12.0 clang
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 -b android-10.0.0_r47 --depth=1
          git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9 -b android-10.0.0_r47 --depth=1
          git clone https://github.com/SakuraNotStupid/AnyKernel3
      - name: Compiling Kernel
        run: |
          CLANG=~/clang/bin
          GCC32=~/arm-linux-androideabi-4.9/bin
          GCC64=~/aarch64-linux-android-4.9/bin
          PATH=$CLANG:$GCC64:$GCC32:$PATH
          args="-j$(nproc --all) \
          O=out \
          ARCH=arm64 \
          CLANG_TRIPLE=aarch64-linux-gnu- \
          CROSS_COMPILE=$GCC64/aarch64-linux-android- \
          CC=$CLANG/clang \
          CROSS_COMPILE_ARM32=$GCC32/arm-linux-androideabi- "
          cd android_kernel_xiaomi_sdm710
          make ${args} sirius_defconfig
          make -j64 ${args}
      - name: 打包内核
        run: |
          cp out/arch/arm64/boot/Image.gz AnyKernel3/
          cd AnyKernel3
          7z a -mx9 ../${{ github.run_number }}_MI8SE-KernelSU_LineageOS20.zip *
      - name: 上传内核
        run: |
          ./transfer trs ${{ github.run_number }}_MI8SE-KernelSU_LineageOS20.zip
